(module
  (memory $memory 306)
  (export "memory" (memory $memory))
  (global $__data_end (export "__data_end") i32 (i32.const 19924000))
  (global $__heap_base (export "__heap_base") i32 (i32.const 19989536))
  (global $__stack_pointer (mut i32) (i32.const 19989536))
  (table $__indirect_function_table 41 funcref)
  (elem (i32.const 1) $rt_align8 $memset $memcpy $memmove $memcmp $strlen $strcpy $strcmp $strncmp $rt_block_at $rt_heap_init $rt_heap_split $rt_heap_coalesce $malloc $free $calloc $realloc $rt_stdio_capacity $rt_stdio_reset $rt_stdin_compact $rt_stdin_set $rt_stdin_append $rt_stdin_remaining $rt_stdout_ptr $rt_stdout_len $rt_stdout_clear $rt_stderr_ptr $rt_stderr_len $rt_stderr_clear $rt_buffer_write $rt_read $rt_write $read $write $rt_getchar $getchar $rt_putchar $putchar $rt_puts $puts)
  (global $__funcidx_11 i32 (i32.const 1))
  (global $__funcidx_12 i32 (i32.const 2))
  (global $__funcidx_13 i32 (i32.const 3))
  (global $__funcidx_14 i32 (i32.const 4))
  (global $__funcidx_15 i32 (i32.const 5))
  (global $__funcidx_16 i32 (i32.const 6))
  (global $__funcidx_17 i32 (i32.const 7))
  (global $__funcidx_18 i32 (i32.const 8))
  (global $__funcidx_19 i32 (i32.const 9))
  (global $__funcidx_20 i32 (i32.const 10))
  (global $__funcidx_21 i32 (i32.const 11))
  (global $__funcidx_22 i32 (i32.const 12))
  (global $__funcidx_23 i32 (i32.const 13))
  (global $__funcidx_24 i32 (i32.const 14))
  (global $__funcidx_25 i32 (i32.const 15))
  (global $__funcidx_26 i32 (i32.const 16))
  (global $__funcidx_27 i32 (i32.const 17))
  (global $__funcidx_28 i32 (i32.const 18))
  (global $__funcidx_29 i32 (i32.const 19))
  (global $__funcidx_30 i32 (i32.const 20))
  (global $__funcidx_31 i32 (i32.const 21))
  (global $__funcidx_32 i32 (i32.const 22))
  (global $__funcidx_33 i32 (i32.const 23))
  (global $__funcidx_34 i32 (i32.const 24))
  (global $__funcidx_35 i32 (i32.const 25))
  (global $__funcidx_36 i32 (i32.const 26))
  (global $__funcidx_37 i32 (i32.const 27))
  (global $__funcidx_38 i32 (i32.const 28))
  (global $__funcidx_39 i32 (i32.const 29))
  (global $__funcidx_40 i32 (i32.const 30))
  (global $__funcidx_41 i32 (i32.const 31))
  (global $__funcidx_42 i32 (i32.const 32))
  (global $__funcidx_43 i32 (i32.const 33))
  (global $__funcidx_44 i32 (i32.const 34))
  (global $__funcidx_45 i32 (i32.const 35))
  (global $__funcidx_46 i32 (i32.const 36))
  (global $__funcidx_47 i32 (i32.const 37))
  (global $__funcidx_48 i32 (i32.const 38))
  (global $__funcidx_49 i32 (i32.const 39))
  (global $__funcidx_50 i32 (i32.const 40))
  (global $__addr_2 i32 (i32.const 1024))
  (global $__addr_3 i32 (i32.const 1049600))
  (global $__addr_4 i32 (i32.const 2098176))
  (global $__addr_5 i32 (i32.const 3146752))
  (global $__addr_6 i32 (i32.const 3146756))
  (global $__addr_7 i32 (i32.const 3146760))
  (global $__addr_8 i32 (i32.const 3146764))
  (global $__addr_9 i32 (i32.const 3146768))
  (global $__addr_10 i32 (i32.const 19923984))
  (func $rt_align8 (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.and (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 7)) (i32.const -8))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $memset (export "memset") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.ge_u (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.load8_u (i32.add (local.get $fp) (i32.const -8))))
          (local.set $r1 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -20)))))
          (i32.store8 (local.get $r1) (local.get $r0))
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $memcpy (export "memcpy") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.ge_u (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r1 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -24)))))
          (local.set $r2 (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -24))))))
          (i32.store8 (local.get $r1) (local.get $r2))
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $memmove (export "memmove") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -20))))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (local.set $pc (i32.const 17))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (if (i32.lt_u (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -20))))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (if (i32.lt_u (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -12)))))
            (then
          (local.set $pc (i32.const 11))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (if (i32.ge_u (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 10))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (local.set $r1 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -24)))))
          (local.set $r2 (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -24))))))
          (i32.store8 (local.get $r1) (local.get $r2))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (local.set $pc (i32.const 16))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 11))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -12))))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 12))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 12))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const 0))
            (then
          (local.set $pc (i32.const 16))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 13))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 13))
        (then
          (local.set $pc (i32.const 15))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 14))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const -1)))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 12))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 15))
        (then
          (local.set $r1 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const 1))))
          (local.set $r2 (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const 1)))))
          (i32.store8 (local.get $r1) (local.get $r2))
          (local.set $pc (i32.const 14))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 16))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (local.set $pc (i32.const 17))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 17))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 18))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $memcmp (export "memcmp") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.ge_u (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 7))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (if (i32.eq (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -24))))) (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -24))))))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.sub (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -24))))) (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -24)))))))
          (local.set $r1 (i32.sub (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -24))))) (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -24)))))))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $r0 (i32.const 0))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $strlen (export "strlen") (param $p0 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.eq (i32.load8_s (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8))))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $strcpy (export "strcpy") (param $p0 i32) (param $p1 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 1)))
          (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 1)))
          (local.set $r2 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (local.set $r2 (i32.load8_s (local.get $r2)))
          (i32.store8 (local.get $r1) (local.get $r2))
          (if (i32.eq (i32.shr_s (i32.shl (local.get $r2) (i32.const 24)) (i32.const 24)) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -12))))
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $strcmp (export "strcmp") (param $p0 i32) (param $p1 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.eq (i32.load8_s (i32.load (i32.add (local.get $fp) (i32.const -4)))) (i32.const 0))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (if (i32.ne (i32.load8_s (i32.load (i32.add (local.get $fp) (i32.const -4)))) (i32.load8_s (i32.load (i32.add (local.get $fp) (i32.const -8)))))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.sub (i32.load8_u (i32.load (i32.add (local.get $fp) (i32.const -4)))) (i32.load8_u (i32.load (i32.add (local.get $fp) (i32.const -8))))))
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $strncmp (export "strncmp") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.ge_u (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 8))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r1 (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -16))))))
          (i32.store8 (i32.add (local.get $fp) (i32.const -17)) (local.get $r1))
          (local.set $r1 (i32.load8_u (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -16))))))
          (i32.store8 (i32.add (local.get $fp) (i32.const -18)) (local.get $r1))
          (if (i32.ne (i32.load8_u (i32.add (local.get $fp) (i32.const -17))) (i32.load8_u (i32.add (local.get $fp) (i32.const -18))))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (if (i32.ne (i32.load8_u (i32.add (local.get $fp) (i32.const -17))) (i32.const 0))
            (then
          (local.set $pc (i32.const 7))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (i32.sub (i32.load8_u (i32.add (local.get $fp) (i32.const -17))) (i32.load8_u (i32.add (local.get $fp) (i32.const -18)))))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (local.set $r0 (i32.const 0))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $rt_block_at (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.add (global.get $__addr_9) (i32.load (i32.add (local.get $fp) (i32.const -4))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $rt_heap_init
    (local $fp i32)
    (local $r0 i32)
    (local $r1 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (if (i32.eq (i32.load (global.get $__addr_10)) (i32.const 0))
      (then
        (local.set $r0 (call $rt_block_at (i32.const 0)))
        (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
        (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
        (local.set $r1 (i32.const 16777204))
        (i32.store (local.get $r0) (local.get $r1))
        (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 4)))
        (local.set $r1 (i32.const -1))
        (i32.store (local.get $r0) (local.get $r1))
        (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 8)))
        (local.set $r1 (i32.const 1))
        (i32.store (local.get $r0) (local.get $r1))
        (local.set $r0 (i32.const 1))
        (i32.store (global.get $__addr_10) (local.get $r0))
      )
      (else
      )
    )
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $rt_heap_split (param $p0 i32) (param $p1 i32)
    (local $fp i32)
    (local $r0 i32)
    (local $r1 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
    (local.set $r0 (call $rt_block_at (i32.load (i32.add (local.get $fp) (i32.const -4)))))
    (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
    (if (i32.ge_u (i32.load (i32.load (i32.add (local.get $fp) (i32.const -12)))) (i32.add (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 12)) (i32.const 8)))
      (then
        (local.set $r0 (i32.add (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 12)) (i32.load (i32.add (local.get $fp) (i32.const -8)))))
        (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
        (local.set $r0 (call $rt_block_at (i32.load (i32.add (local.get $fp) (i32.const -20)))))
        (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
        (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -16))))
        (local.set $r1 (i32.sub (i32.sub (i32.load (i32.load (i32.add (local.get $fp) (i32.const -12)))) (i32.load (i32.add (local.get $fp) (i32.const -8)))) (i32.const 12)))
        (i32.store (local.get $r0) (local.get $r1))
        (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 4)))
        (local.set $r1 (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 4))))
        (i32.store (local.get $r0) (local.get $r1))
        (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 8)))
        (local.set $r1 (i32.const 1))
        (i32.store (local.get $r0) (local.get $r1))
        (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -12))))
        (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -8))))
        (i32.store (local.get $r0) (local.get $r1))
        (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 4)))
        (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -20))))
        (i32.store (local.get $r0) (local.get $r1))
      )
      (else
      )
    )
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $rt_heap_coalesce
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const -1))
            (then
          (local.set $pc (i32.const 7))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (call $rt_block_at (i32.load (i32.add (local.get $fp) (i32.const -4)))))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (if (i32.eq (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (if (i32.eq (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 4))) (i32.const -1))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (call $rt_block_at (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 4)))))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (if (i32.eq (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (local.set $r1 (i32.add (i32.load (i32.load (i32.add (local.get $fp) (i32.const -12)))) (i32.const 12)))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $r0 (i32.add (i32.load (local.get $r0)) (local.get $r1)))
          (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -16))))
          (i32.store (local.get $r1) (local.get $r0))
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 4)))
          (local.set $r1 (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 4))))
          (i32.store (local.get $r0) (local.get $r1))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 4))))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return)
        )
      )
      (unreachable)
    )
  )
  (func $malloc (export "malloc") (param $p0 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (call $rt_heap_init)
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 0))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $r0 (i32.const 1))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (call $rt_align8 (i32.load (i32.add (local.get $fp) (i32.const -4)))))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
          (local.set $r0 (i32.const 0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const -1))
            (then
          (local.set $pc (i32.const 10))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (call $rt_block_at (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (local.set $r0 (i32.load (i32.add (local.get $r0) (i32.const 4))))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (call $rt_block_at (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (if (i32.eq (i32.load (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 9))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (if (i32.lt_u (i32.load (i32.load (i32.add (local.get $fp) (i32.const -12)))) (i32.load (i32.add (local.get $fp) (i32.const -4))))
            (then
          (local.set $pc (i32.const 9))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (call $rt_heap_split (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 8)))
          (local.set $r1 (i32.const 0))
          (i32.store (local.get $r0) (local.get $r1))
          (local.set $r0 (i32.add (i32.add (global.get $__addr_9) (i32.load (i32.add (local.get $fp) (i32.const -8)))) (i32.const 12)))
          (local.set $r1 (i32.add (i32.add (global.get $__addr_9) (i32.load (i32.add (local.get $fp) (i32.const -8)))) (i32.const 12)))
          (local.set $pc (i32.const 11))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (local.set $r0 (i32.const 0))
          (local.set $pc (i32.const 11))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 11))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 12))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $free (export "free") (param $p0 i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 0))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -4))) (global.get $__addr_9)))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (if (i32.lt_u (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 12))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (if (i32.lt_u (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 16777216))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 12)))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (local.set $r0 (call $rt_block_at (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 8)))
          (local.set $r1 (i32.const 1))
          (i32.store (local.get $r0) (local.get $r1))
          (call $rt_heap_coalesce)
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return)
        )
      )
      (unreachable)
    )
  )
  (func $calloc (export "calloc") (param $p0 i32) (param $p1 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.le_u (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.div_u (i32.const -1) (i32.load (i32.add (local.get $fp) (i32.const -8)))))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (i32.const 0))
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.mul (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $r0 (call $malloc (i32.load (i32.add (local.get $fp) (i32.const -16)))))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 0))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (call $memset (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 0) (i32.load (i32.add (local.get $fp) (i32.const -16)))))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -12))))
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $realloc (export "realloc") (param $p0 i32) (param $p1 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 0))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $r0 (call $malloc (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (call $free (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (local.set $r0 (i32.const 0))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (call $rt_block_at (i32.sub (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -4))) (global.get $__addr_9)) (i32.const 12))))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (local.set $r0 (i32.load (i32.load (i32.add (local.get $fp) (i32.const -20)))))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (local.set $r0 (call $rt_align8 (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (if (i32.gt_u (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (call $rt_heap_split (i32.sub (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -4))) (global.get $__addr_9)) (i32.const 12)) (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (call $malloc (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 0))
            (then
          (local.set $pc (i32.const 8))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $r0 (i32.const 0))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (local.set $r0 (call $memcpy (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -12)))))
          (call $free (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -16))))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $rt_stdio_capacity (export "rt_stdio_capacity") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.const 1048576)
    (return)
  )
  (func $rt_stdio_reset (export "rt_stdio_reset")
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (local.set $r0 (i32.const 0))
    (i32.store (global.get $__addr_5) (local.get $r0))
    (local.set $r0 (i32.const 0))
    (i32.store (global.get $__addr_6) (local.get $r0))
    (local.set $r0 (i32.const 0))
    (i32.store (global.get $__addr_7) (local.get $r0))
    (local.set $r0 (i32.const 0))
    (i32.store (global.get $__addr_8) (local.get $r0))
    (return)
  )
  (func $rt_stdin_compact
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (if (i32.ne (i32.load (global.get $__addr_6)) (i32.const 0))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (if (i32.lt_u (i32.load (global.get $__addr_6)) (i32.load (global.get $__addr_5)))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.const 0))
          (i32.store (global.get $__addr_5) (local.get $r0))
          (local.set $r0 (i32.const 0))
          (i32.store (global.get $__addr_6) (local.get $r0))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.sub (i32.load (global.get $__addr_5)) (i32.load (global.get $__addr_6))))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r0))
          (local.set $r0 (call $memmove (global.get $__addr_2) (i32.add (global.get $__addr_2) (i32.load (global.get $__addr_6))) (i32.load (i32.add (local.get $fp) (i32.const -4)))))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
          (local.set $r1 (i32.add (global.get $__addr_2) (i32.load (global.get $__addr_6))))
          (i32.store (global.get $__addr_5) (local.get $r0))
          (local.set $r0 (i32.const 0))
          (i32.store (global.get $__addr_6) (local.get $r0))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return)
        )
      )
      (unreachable)
    )
  )
  (func $rt_stdin_set (export "rt_stdin_set") (param $p0 i32) (param $p1 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (i32.const -22))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (if (i32.le_u (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 1048576))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.const -28))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 7))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (call $memcpy (global.get $__addr_2) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (i32.store (global.get $__addr_5) (local.get $r0))
          (local.set $r0 (i32.const 0))
          (i32.store (global.get $__addr_6) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $rt_stdin_append (export "rt_stdin_append") (param $p0 i32) (param $p1 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (i32.const -22))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (call $rt_stdin_compact)
          (if (i32.le_u (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.sub (i32.const 1048576) (i32.load (global.get $__addr_5))))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.const -28))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 7))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (call $memcpy (i32.add (global.get $__addr_2) (i32.load (global.get $__addr_5))) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (local.set $r1 (i32.add (global.get $__addr_2) (i32.load (global.get $__addr_5))))
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $r0 (i32.add (i32.load (global.get $__addr_5)) (i32.load (i32.add (local.get $fp) (i32.const -8)))))
          (i32.store (global.get $__addr_5) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $rt_stdin_remaining (export "rt_stdin_remaining") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.sub (i32.load (global.get $__addr_5)) (i32.load (global.get $__addr_6)))
    (return)
  )
  (func $rt_stdout_ptr (export "rt_stdout_ptr") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.get $__addr_3)
    (return)
  )
  (func $rt_stdout_len (export "rt_stdout_len") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.load (global.get $__addr_7))
    (return)
  )
  (func $rt_stdout_clear (export "rt_stdout_clear")
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (local.set $r0 (i32.const 0))
    (i32.store (global.get $__addr_7) (local.get $r0))
    (return)
  )
  (func $rt_stderr_ptr (export "rt_stderr_ptr") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.get $__addr_4)
    (return)
  )
  (func $rt_stderr_len (export "rt_stderr_len") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.load (global.get $__addr_8))
    (return)
  )
  (func $rt_stderr_clear (export "rt_stderr_clear")
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (local.set $r0 (i32.const 0))
    (i32.store (global.get $__addr_8) (local.get $r0))
    (return)
  )
  (func $rt_buffer_write (param $p0 i32) (param $p1 i32) (param $p2 i32) (param $p3 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $p3))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 0))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (i32.const -22))
          (local.set $pc (i32.const 11))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r1 (i32.sub (i32.const 1048576) (i32.load (i32.load (i32.add (local.get $fp) (i32.const -8))))))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r1))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.const 0))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 0))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.const -28))
          (local.set $pc (i32.const 11))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -16))))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (if (i32.le_u (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.load (i32.add (local.get $fp) (i32.const -20))))
            (then
          (local.set $pc (i32.const 8))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -20))))
          (i32.store (i32.add (local.get $fp) (i32.const -24)) (local.get $r0))
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -24))) (i32.const 0))
            (then
          (local.set $pc (i32.const 10))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (local.set $r0 (call $memcpy (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.load (i32.add (local.get $fp) (i32.const -8))))) (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.load (i32.add (local.get $fp) (i32.const -24)))))
          (local.set $r1 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.load (i32.add (local.get $fp) (i32.const -8))))))
          (local.set $pc (i32.const 10))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
          (i32.store (i32.add (local.get $fp) (i32.const -28)) (local.get $r0))
          (local.set $r0 (i32.add (i32.load (local.get $r0)) (i32.load (i32.add (local.get $fp) (i32.const -24)))))
          (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -28))))
          (i32.store (local.get $r1) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -24))))
          (local.set $pc (i32.const 11))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 11))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 12))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $rt_read (export "rt_read") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 32)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 0))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $r0 (i32.const -9))
          (local.set $pc (i32.const 10))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 0))
            (then
          (local.set $pc (i32.const 5))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.const -22))
          (local.set $pc (i32.const 10))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.sub (i32.load (global.get $__addr_5)) (i32.load (global.get $__addr_6))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -12))))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (if (i32.le_u (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.load (i32.add (local.get $fp) (i32.const -16))))
            (then
          (local.set $pc (i32.const 7))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 6))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -16))))
          (i32.store (i32.add (local.get $fp) (i32.const -20)) (local.get $r0))
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -20))) (i32.const 0))
            (then
          (local.set $pc (i32.const 9))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (local.set $r0 (call $memcpy (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.add (global.get $__addr_2) (i32.load (global.get $__addr_6))) (i32.load (i32.add (local.get $fp) (i32.const -20)))))
          (local.set $r1 (i32.add (global.get $__addr_2) (i32.load (global.get $__addr_6))))
          (local.set $pc (i32.const 9))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (local.set $r0 (i32.add (i32.load (global.get $__addr_6)) (i32.load (i32.add (local.get $fp) (i32.const -20)))))
          (i32.store (global.get $__addr_6) (local.get $r0))
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -20))))
          (local.set $pc (i32.const 10))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 11))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $rt_write (export "rt_write") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 1))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $r0 (call $rt_buffer_write (global.get $__addr_3) (global.get $__addr_7) (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -12)))))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 2))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (call $rt_buffer_write (global.get $__addr_4) (global.get $__addr_8) (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -12)))))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.const -9))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $read (export "read") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
    (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
    (call $rt_read (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $write (export "write") (param $p0 i32) (param $p1 i32) (param $p2 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
    (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $p2))
    (call $rt_write (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $rt_getchar (export "rt_getchar") (result i32)
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $r0 (call $rt_read (i32.const 0) (i32.add (local.get $fp) (i32.const -1)) (i32.const 1)))
    (if (result i32) (i32.eq (local.get $r0) (i32.const 1))
      (then
        (i32.load8_u (i32.add (local.get $fp) (i32.const -1)))
      )
      (else
        (i32.const -1)
      )
    )
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $getchar (export "getchar") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (call $rt_getchar)
    (return)
  )
  (func $rt_putchar (export "rt_putchar") (param $p0 i32) (result i32)
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (local.set $r0 (i32.load8_u (i32.add (local.get $fp) (i32.const -4))))
    (i32.store8 (i32.add (local.get $fp) (i32.const -5)) (local.get $r0))
    (local.set $r0 (call $rt_write (i32.const 1) (i32.add (local.get $fp) (i32.const -5)) (i32.const 1)))
    (if (result i32) (i32.eq (local.get $r0) (i32.const 1))
      (then
        (i32.load8_u (i32.add (local.get $fp) (i32.const -5)))
      )
      (else
        (i32.const -1)
      )
    )
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $putchar (export "putchar") (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (call $rt_putchar (i32.load (i32.add (local.get $fp) (i32.const -4))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $rt_puts (export "rt_puts") (param $p0 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (local.set $r0 (i32.const 10))
          (i32.store8 (i32.add (local.get $fp) (i32.const -5)) (local.get $r0))
          (if (i32.ne (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 0))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $r0 (i32.const -22))
          (local.set $pc (i32.const 13))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (call $strlen (i32.load (i32.add (local.get $fp) (i32.const -4)))))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (local.set $r0 (call $rt_write (i32.const 1) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -12)))))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (if (i32.ge_s (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 0))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -16))))
          (local.set $pc (i32.const 13))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 6))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (local.set $r0 (i32.const -28))
          (local.set $pc (i32.const 13))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (local.set $r0 (call $rt_write (i32.const 1) (i32.add (local.get $fp) (i32.const -5)) (i32.const 1)))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 1))
            (then
          (local.set $pc (i32.const 12))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 7))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 7))
        (then
          (if (i32.ge_s (i32.load (i32.add (local.get $fp) (i32.const -16))) (i32.const 0))
            (then
          (local.set $pc (i32.const 9))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 8))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 8))
        (then
          (local.set $pc (i32.const 10))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 9))
        (then
          (local.set $r0 (i32.const -28))
          (local.set $pc (i32.const 11))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 10))
        (then
          (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -16))))
          (local.set $pc (i32.const 11))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 11))
        (then
          (local.set $pc (i32.const 13))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 12))
        (then
          (local.set $r0 (i32.add (i32.load (i32.add (local.get $fp) (i32.const -12))) (i32.const 1)))
          (local.set $pc (i32.const 13))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 13))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 14))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $puts (export "puts") (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (call $rt_puts (i32.load (i32.add (local.get $fp) (i32.const -4))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
)
