(module
  (memory $memory 2)
  (export "memory" (memory $memory))
  (global $__data_end (export "__data_end") i32 (i32.const 1024))
  (global $__heap_base (export "__heap_base") i32 (i32.const 66560))
  (global $__stack_pointer (mut i32) (i32.const 66560))
  (table $__indirect_function_table 4 funcref)
  (elem (i32.const 1) $add $fib $answer)
  (global $__funcidx_2 i32 (i32.const 1))
  (global $__funcidx_3 i32 (i32.const 2))
  (global $__funcidx_4 i32 (i32.const 3))
  (func $memset (param $dst i32) (param $val i32) (param $n i32) (result i32)
    (local $p i32)
    (local $end i32)
    (local.set $p (local.get $dst))
    (local.set $end (i32.add (local.get $dst) (local.get $n)))
    (loop $loop
      (if (i32.lt_u (local.get $p) (local.get $end))
        (then
          (i32.store8 (local.get $p) (local.get $val))
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (br $loop)
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memmove (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (local $d i32)
    (local $s i32)
    (local $end i32)
    (if (i32.or (i32.le_u (local.get $dst) (local.get $src)) (i32.ge_u (local.get $dst) (i32.add (local.get $src) (local.get $n))))
      (then
        (local.set $d (local.get $dst))
        (local.set $s (local.get $src))
        (local.set $end (i32.add (local.get $dst) (local.get $n)))
        (loop $forward
          (if (i32.lt_u (local.get $d) (local.get $end))
            (then
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $d (i32.add (local.get $d) (i32.const 1)))
              (local.set $s (i32.add (local.get $s) (i32.const 1)))
              (br $forward)
            )
          )
        )
      )
      (else
        (local.set $d (i32.add (local.get $dst) (local.get $n)))
        (local.set $s (i32.add (local.get $src) (local.get $n)))
        (loop $backward
          (if (local.get $n)
            (then
              (local.set $d (i32.sub (local.get $d) (i32.const 1)))
              (local.set $s (i32.sub (local.get $s) (i32.const 1)))
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $n (i32.sub (local.get $n) (i32.const 1)))
              (br $backward)
            )
          )
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memcpy (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (return (call $memmove (local.get $dst) (local.get $src) (local.get $n)))
  )
  (func $add (export "add") (param $p0 i32) (param $p1 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
    (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $fib (export "fib") (param $p0 i32) (result i32)
    (local $fp i32)
    (local $r0 i32)
    (local $r1 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (if (result i32) (i32.ge_s (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 2))
      (then
        (local.set $r0 (call $fib (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 1))))
        (local.set $r1 (i32.sub (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 2)))
        (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
        (local.set $r0 (call $fib (local.get $r1)))
        (i32.add (i32.load (i32.add (local.get $fp) (i32.const -8))) (local.get $r0))
      )
      (else
        (i32.load (i32.add (local.get $fp) (i32.const -4)))
      )
    )
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $answer (export "answer") (result i32)
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (local.set $r0 (call $fib (i32.const 6)))
    (call $add (local.get $r0) (i32.const 4))
    (return)
  )
)
