(module
  (memory $memory 2)
  (export "memory" (memory $memory))
  (global $__data_end (export "__data_end") i32 (i32.const 1040))
  (global $__heap_base (export "__heap_base") i32 (i32.const 66576))
  (global $__stack_pointer (mut i32) (i32.const 66576))
  (type $ft0 (func (param i32) (result i32)))
  (type $ft1 (func (param i32)))
  (table $__indirect_function_table 8 funcref)
  (elem (i32.const 1) $inc1 $add2 $set_side $call_local_fp $call_global_fp $call_selected_fp $call_void_fp)
  (global $__funcidx_2 i32 (i32.const 1))
  (global $__funcidx_3 i32 (i32.const 2))
  (global $__funcidx_6 i32 (i32.const 3))
  (global $__funcidx_8 i32 (i32.const 4))
  (global $__funcidx_9 i32 (i32.const 5))
  (global $__funcidx_10 i32 (i32.const 6))
  (global $__funcidx_11 i32 (i32.const 7))
  (global $__addr_4 i32 (i32.const 1024))
  (global $__addr_5 i32 (i32.const 1032))
  (global $__addr_7 i32 (i32.const 1028))
  (data (i32.const 1024) "\01\00\00\00\03\00\00\00")
  (func $memset (param $dst i32) (param $val i32) (param $n i32) (result i32)
    (local $p i32)
    (local $end i32)
    (local.set $p (local.get $dst))
    (local.set $end (i32.add (local.get $dst) (local.get $n)))
    (loop $loop
      (if (i32.lt_u (local.get $p) (local.get $end))
        (then
          (i32.store8 (local.get $p) (local.get $val))
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (br $loop)
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memmove (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (local $d i32)
    (local $s i32)
    (local $end i32)
    (if (i32.or (i32.le_u (local.get $dst) (local.get $src)) (i32.ge_u (local.get $dst) (i32.add (local.get $src) (local.get $n))))
      (then
        (local.set $d (local.get $dst))
        (local.set $s (local.get $src))
        (local.set $end (i32.add (local.get $dst) (local.get $n)))
        (loop $forward
          (if (i32.lt_u (local.get $d) (local.get $end))
            (then
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $d (i32.add (local.get $d) (i32.const 1)))
              (local.set $s (i32.add (local.get $s) (i32.const 1)))
              (br $forward)
            )
          )
        )
      )
      (else
        (local.set $d (i32.add (local.get $dst) (local.get $n)))
        (local.set $s (i32.add (local.get $src) (local.get $n)))
        (loop $backward
          (if (local.get $n)
            (then
              (local.set $d (i32.sub (local.get $d) (i32.const 1)))
              (local.set $s (i32.sub (local.get $s) (i32.const 1)))
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $n (i32.sub (local.get $n) (i32.const 1)))
              (br $backward)
            )
          )
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memcpy (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (return (call $memmove (local.get $dst) (local.get $src) (local.get $n)))
  )
  (func $inc1 (export "inc1") (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 1))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $add2 (export "add2") (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.add (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 2))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $set_side (export "set_side") (param $p0 i32)
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
    (i32.store (global.get $__addr_5) (local.get $r0))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $call_local_fp (export "call_local_fp") (param $p0 i32) (result i32)
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (local.set $r0 (global.get $__funcidx_3))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
    (call_indirect (type $ft0) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -8))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $call_global_fp (export "call_global_fp") (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (call_indirect (type $ft0) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (global.get $__addr_4)))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $call_selected_fp (export "call_selected_fp") (param $p0 i32) (param $p1 i32) (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $p1))
          (if (i32.eq (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.const 0))
            (then
          (local.set $pc (i32.const 2))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (local.set $r0 (global.get $__funcidx_2))
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (global.get $__funcidx_3))
          (local.set $pc (i32.const 4))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r0))
          (local.set $r0 (call_indirect (type $ft0) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -12)))))
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
  (func $call_void_fp (export "call_void_fp") (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (call_indirect (type $ft1) (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (global.get $__addr_7)))
    (i32.load (global.get $__addr_5))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
)
