(module
  (memory $memory 2)
  (export "memory" (memory $memory))
  (global $__data_end (export "__data_end") i32 (i32.const 1056))
  (global $__heap_base (export "__heap_base") i32 (i32.const 66592))
  (global $__stack_pointer (mut i32) (i32.const 66592))
  (table $__indirect_function_table 7 funcref)
  (elem (i32.const 1) $get_g $set_g $get_arr $get_msg1 $get_msgp2 $get_lit1)
  (global $__funcidx_6 i32 (i32.const 1))
  (global $__funcidx_7 i32 (i32.const 2))
  (global $__funcidx_8 i32 (i32.const 3))
  (global $__funcidx_9 i32 (i32.const 4))
  (global $__funcidx_10 i32 (i32.const 5))
  (global $__funcidx_11 i32 (i32.const 6))
  (global $__addr_2 i32 (i32.const 1024))
  (global $__addr_3 i32 (i32.const 1028))
  (global $__addr_4 i32 (i32.const 1040))
  (global $__addr_5 i32 (i32.const 1044))
  (global $__addr_12 i32 (i32.const 1048))
  (data (i32.const 1024) "\07\00\00\00\0b\00\00\00\16\00\00\00!\00\00\00abc\00\10\04\00\00")
  (data (i32.const 1048) "xy\00")
  (func $memset (param $dst i32) (param $val i32) (param $n i32) (result i32)
    (local $p i32)
    (local $end i32)
    (local.set $p (local.get $dst))
    (local.set $end (i32.add (local.get $dst) (local.get $n)))
    (loop $loop
      (if (i32.lt_u (local.get $p) (local.get $end))
        (then
          (i32.store8 (local.get $p) (local.get $val))
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (br $loop)
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memmove (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (local $d i32)
    (local $s i32)
    (local $end i32)
    (if (i32.or (i32.le_u (local.get $dst) (local.get $src)) (i32.ge_u (local.get $dst) (i32.add (local.get $src) (local.get $n))))
      (then
        (local.set $d (local.get $dst))
        (local.set $s (local.get $src))
        (local.set $end (i32.add (local.get $dst) (local.get $n)))
        (loop $forward
          (if (i32.lt_u (local.get $d) (local.get $end))
            (then
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $d (i32.add (local.get $d) (i32.const 1)))
              (local.set $s (i32.add (local.get $s) (i32.const 1)))
              (br $forward)
            )
          )
        )
      )
      (else
        (local.set $d (i32.add (local.get $dst) (local.get $n)))
        (local.set $s (i32.add (local.get $src) (local.get $n)))
        (loop $backward
          (if (local.get $n)
            (then
              (local.set $d (i32.sub (local.get $d) (i32.const 1)))
              (local.set $s (i32.sub (local.get $s) (i32.const 1)))
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $n (i32.sub (local.get $n) (i32.const 1)))
              (br $backward)
            )
          )
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memcpy (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (return (call $memmove (local.get $dst) (local.get $src) (local.get $n)))
  )
  (func $get_g (export "get_g") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.load (global.get $__addr_2))
    (return)
  )
  (func $set_g (export "set_g") (param $p0 i32)
    (local $fp i32)
    (local $r0 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -4))))
    (i32.store (global.get $__addr_2) (local.get $r0))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $get_arr (export "get_arr") (param $p0 i32) (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $p0))
    (i32.load (i32.add (global.get $__addr_3) (i32.shl (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.const 2))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $get_msg1 (export "get_msg1") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.load8_s (i32.add (global.get $__addr_4) (i32.const 1)))
    (return)
  )
  (func $get_msgp2 (export "get_msgp2") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.load8_s (i32.add (i32.load (global.get $__addr_5)) (i32.const 2)))
    (return)
  )
  (func $get_lit1 (export "get_lit1") (result i32)
    (local $fp i32)
    (local.set $fp (global.get $__stack_pointer))
    (i32.load8_s (i32.add (global.get $__addr_12) (i32.const 1)))
    (return)
  )
)
