(module
  (memory $memory 2)
  (export "memory" (memory $memory))
  (global $__data_end (export "__data_end") i32 (i32.const 1024))
  (global $__heap_base (export "__heap_base") i32 (i32.const 66560))
  (global $__stack_pointer (mut i32) (i32.const 66560))
  (table $__indirect_function_table 5 funcref)
  (elem (i32.const 1) $ll_add_low $ll_sub_borrow_low $ll_mul_low $ll_cmp)
  (global $__funcidx_2 i32 (i32.const 1))
  (global $__funcidx_3 i32 (i32.const 2))
  (global $__funcidx_4 i32 (i32.const 3))
  (global $__funcidx_5 i32 (i32.const 4))
  (func $memset (param $dst i32) (param $val i32) (param $n i32) (result i32)
    (local $p i32)
    (local $end i32)
    (local.set $p (local.get $dst))
    (local.set $end (i32.add (local.get $dst) (local.get $n)))
    (loop $loop
      (if (i32.lt_u (local.get $p) (local.get $end))
        (then
          (i32.store8 (local.get $p) (local.get $val))
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (br $loop)
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memmove (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (local $d i32)
    (local $s i32)
    (local $end i32)
    (if (i32.or (i32.le_u (local.get $dst) (local.get $src)) (i32.ge_u (local.get $dst) (i32.add (local.get $src) (local.get $n))))
      (then
        (local.set $d (local.get $dst))
        (local.set $s (local.get $src))
        (local.set $end (i32.add (local.get $dst) (local.get $n)))
        (loop $forward
          (if (i32.lt_u (local.get $d) (local.get $end))
            (then
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $d (i32.add (local.get $d) (i32.const 1)))
              (local.set $s (i32.add (local.get $s) (i32.const 1)))
              (br $forward)
            )
          )
        )
      )
      (else
        (local.set $d (i32.add (local.get $dst) (local.get $n)))
        (local.set $s (i32.add (local.get $src) (local.get $n)))
        (loop $backward
          (if (local.get $n)
            (then
              (local.set $d (i32.sub (local.get $d) (i32.const 1)))
              (local.set $s (i32.sub (local.get $s) (i32.const 1)))
              (i32.store8 (local.get $d) (i32.load8_u (local.get $s)))
              (local.set $n (i32.sub (local.get $n) (i32.const 1)))
              (br $backward)
            )
          )
        )
      )
    )
    (return (local.get $dst))
  )
  (func $memcpy (param $dst i32) (param $src i32) (param $n i32) (result i32)
    (return (call $memmove (local.get $dst) (local.get $src) (local.get $n)))
  )
  (func $ll_add_low (export "ll_add_low") (result i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $r0 (i32.const 2147483647))
    (local.set $r1 (i32.const 0))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r1))
    (local.set $r0 (i32.const 5))
    (local.set $r1 (i32.const 0))
    (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
    (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r1))
    (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
    (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -16))))
    (local.set $carry (i32.lt_u (i32.add (local.get $r0) (local.get $r1)) (local.get $r0)))
    (local.set $r0 (i32.add (local.get $r0) (local.get $r1)))
    (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -4))))
    (local.set $r2 (i32.load (i32.add (local.get $fp) (i32.const -12))))
    (local.set $r1 (i32.add (i32.add (local.get $r1) (local.get $r2)) (local.get $carry)))
    (global.set $__stack_pointer (local.get $fp))
    (return (local.get $r0))
  )
  (func $ll_sub_borrow_low (export "ll_sub_borrow_low") (result i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $r0 (i32.const 0))
    (local.set $r1 (i32.const 1))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r1))
    (local.set $r0 (i32.const 1))
    (local.set $r1 (i32.const 0))
    (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
    (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r1))
    (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
    (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -16))))
    (local.set $carry (i32.lt_u (local.get $r0) (local.get $r1)))
    (local.set $r0 (i32.sub (local.get $r0) (local.get $r1)))
    (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -4))))
    (local.set $r2 (i32.load (i32.add (local.get $fp) (i32.const -12))))
    (local.set $r1 (i32.sub (i32.sub (local.get $r1) (local.get $r2)) (local.get $carry)))
    (global.set $__stack_pointer (local.get $fp))
    (return (local.get $r0))
  )
  (func $ll_mul_low (export "ll_mul_low") (result i32)
    (local $fp i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $r0 (i32.const 65537))
    (local.set $r1 (i32.const 0))
    (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
    (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r1))
    (local.set $r0 (i32.const 65539))
    (local.set $r1 (i32.const 0))
    (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
    (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r1))
    (local.set $r0 (i32.load (i32.add (local.get $fp) (i32.const -8))))
    (local.set $r1 (i32.load (i32.add (local.get $fp) (i32.const -16))))
    (local.set $r2 (i32.wrap_i64 (i64.shr_u (i64.mul (i64.extend_i32_u (local.get $r0)) (i64.extend_i32_u (local.get $r1))) (i64.const 32))))
    (i32.wrap_i64 (i64.mul (i64.extend_i32_u (local.get $r0)) (i64.extend_i32_u (local.get $r1))))
    (global.set $__stack_pointer (local.get $fp))
    (return)
  )
  (func $ll_cmp (export "ll_cmp") (result i32)
    (local $pc i32)
    (local $fp i32)
    (local $carry i32)
    (local $r0 i32)
    (local $r1 i32)
    (local $r2 i32)
    (local $r3 i32)
    (local $r4 i32)
    (local $r5 i32)
    (local $r6 i32)
    (local $r7 i32)
    (local.set $fp (global.get $__stack_pointer))
    (global.set $__stack_pointer (i32.sub (local.get $fp) (i32.const 16)))
    (local.set $pc (i32.const 0))
    (loop $dispatch
      (if (i32.eq (local.get $pc) (i32.const 0))
        (then
          (local.set $r0 (i32.const 1))
          (local.set $r1 (i32.const 1))
          (i32.store (i32.add (local.get $fp) (i32.const -8)) (local.get $r0))
          (i32.store (i32.add (local.get $fp) (i32.const -4)) (local.get $r1))
          (local.set $r0 (i32.const 0))
          (local.set $r1 (i32.const 1))
          (i32.store (i32.add (local.get $fp) (i32.const -16)) (local.get $r0))
          (i32.store (i32.add (local.get $fp) (i32.const -12)) (local.get $r1))
          (if (i32.lt_s (i32.load (i32.add (local.get $fp) (i32.const -4))) (i32.load (i32.add (local.get $fp) (i32.const -12))))
            (then
          (local.set $pc (i32.const 3))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 1))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 1))
        (then
          (if (i32.ne (local.get $r0) (local.get $r0))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 2))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 2))
        (then
          (if (i32.gt_u (i32.load (i32.add (local.get $fp) (i32.const -8))) (i32.load (i32.add (local.get $fp) (i32.const -16))))
            (then
          (local.set $pc (i32.const 4))
          (br $dispatch)
            )
          )
          (local.set $pc (i32.const 3))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 3))
        (then
          (local.set $r0 (i32.const 0))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 4))
        (then
          (local.set $r0 (i32.const 1))
          (local.set $pc (i32.const 5))
          (br $dispatch)
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 5))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (if (i32.eq (local.get $pc) (i32.const 6))
        (then
          (global.set $__stack_pointer (local.get $fp))
          (return (local.get $r0))
        )
      )
      (unreachable)
    )
  )
)
